### ISSUE TITLE
Getting Errors After Installing Theme

### ISSUE THREAD

**Issue by lilbogglr** [deependhulla/brightsmartbt3-htmly#1]
I get the following errors when I try to use theme

Warning: require(themes/brightsmartbt3/layout.html.php): failed to open stream: No such file or directory in /home4/lilboggle/public_html/curation/system/includes/dispatch.php on line 351

Warning: require(themes/brightsmartbt3/layout.html.php): failed to open stream: No such file or directory in /home4/lilboggle/public_html/curation/system/includes/dispatch.php on line 351

Fatal error: require(): Failed opening required 'themes/brightsmartbt3/layout.html.php' (include_path='.:/opt/php56/lib/php') in /home4/lilboggle/public_html/curation/system/includes/dispatch.php on line 351

I have Installed Version: v2.7.4 of HTMLY
Any help or ideas would be appreciated

**Comment by deependhulla** [comment]
Hard to understand your from your error.  seems like theme is not copied in proper required location as per your server setup.
